<?php
// summary stats for RAO
$query_RAO_summary_stats2 =
"select 
avg_changeset_send_time        = AVG(avg_changeset_send_time       ),
avg_oper_process_time          = AVG(avg_oper_process_time         ),
avg_ops_per_transaction        = AVG(avg_ops_per_transaction       ),
avg_sender_oper_process_time   = AVG(avg_sender_oper_process_time  ),
avg_sender_oper_wait_time      = AVG(avg_sender_oper_wait_time     ),
avg_xlog_oper_wait_time        = AVG(avg_xlog_oper_wait_time       ),
current_marked_obj_cache_size  = AVG(current_marked_obj_cache_size ),
current_oper_queue_size        = AVG(current_oper_queue_size       ),
current_scan_buffer_size       = AVG(current_scan_buffer_size      ),
current_session_cache_size     = AVG(current_session_cache_size    ),
maint_user_opers_filtered      = SUM(maint_user_opers_filtered     ),
opers_processed                = SUM(opers_processed               ),
opers_scanned                  = SUM(opers_scanned                 ),
opers_skipped                  = SUM(opers_skipped                 ),
sender_opers_processed         = SUM(sender_opers_processed        ),
system_transactions_skipped    = SUM(system_transactions_skipped   ),
transactions_aborted           = SUM(transactions_aborted          ),
transactions_closed            = SUM(transactions_closed           ),
transactions_committed         = SUM(transactions_committed        ),
transactions_opened            = SUM(transactions_opened           ),
transactions_processed         = SUM(transactions_processed        ),
transactions_skipped           = SUM(transactions_skipped          ),
avg_bytes_second_during_trans  = AVG(avg_bytes_second_during_trans ),
avg_data_arrival_time          = AVG(avg_data_arrival_time         ),
avg_ltl_buffer_cache_time      = AVG(avg_ltl_buffer_cache_time     ),
avg_ltl_buffer_size            = AVG(avg_ltl_buffer_size           ),
avg_ltl_command_size           = AVG(avg_ltl_command_size          ),
avg_ltl_commands_buffer        = AVG(avg_ltl_commands_buffer       ),
avg_ltl_commands_sec           = AVG(avg_ltl_commands_sec          ),
avg_ltm_buffer_utilization     = AVG(avg_ltm_buffer_utilization    ),
avg_rep_srvr_turnaround_time   = AVG(avg_rep_srvr_turnaround_time  ),
avg_time_to_create_distrib     = AVG(avg_time_to_create_distrib    ),
encoded_column_name_cache_size = AVG(encoded_column_name_cache_size),
input_queue_size               = AVG(input_queue_size              ),
number_of_ltl_commands_sent    = SUM(number_of_ltl_commands_sent   ),
output_queue_size              = SUM(output_queue_size             ),
bytes_sent                     = SUM(bytes_sent                    ),
items_held_in_global_lrucache  = AVG(items_held_in_global_lrucache ),
vm__max_memory_used            = MAX(vm__max_memory_used           ),
vm_free_memory                 = AVG(vm_free_memory                ),
vm_maximum_memory              = MAX(vm_maximum_memory             ),
vm_memory_usage                = AVG(vm_memory_usage               ),
vm_total_memory_allocated      = MAX(vm_total_memory_allocated     ),
avg_RBA_search_time            = AVG(avg_RBA_search_time           ),
avg_number_of_bytes_per_record = AVG(avg_number_of_bytes_per_record),
avg_number_of_bytes_read_per_s = AVG(avg_number_of_bytes_read_per_s),
avg_nb_of_log_records_per_ckpt = AVG(avg_nb_of_log_records_per_ckpt),
avg_nb_of_s_between_log_r_ckpt = AVG(avg_nb_of_s_between_log_r_ckpt),
avg_time_per_arch_log_dev_read = AVG(avg_time_per_arch_log_dev_read),
avg_time_per_onln_log_dev_read = AVG(avg_time_per_onln_log_dev_read),
Curr_RASD_article_cache_size   = AVG(Curr_RASD_article_cache_size  ),
Cur_RASD_marked_obj_cache_size = AVG(Cur_RASD_marked_obj_cache_size),
Log_scan_checkpoint_set_size   = AVG(Log_scan_checkpoint_set_size  ),
Total_archive_log_read_time    = SUM(Total_archive_log_read_time   ),
Total_bytes_read               = SUM(Total_bytes_read              ),
Total_log_records_filtered     = SUM(Total_log_records_filtered    ),
Total_log_records_queued       = SUM(Total_log_records_queued      ),
Total_log_records_read         = SUM(Total_log_records_read        ),
TotNum_of_RASD_art_cache_hits  = SUM(TotNum_of_RASD_art_cache_hits ),
TotNum_of_RASD_art_cache_miss  = SUM(TotNum_of_RASD_art_cache_miss ),
TotNum_of_RASD_marked_obj_hits = SUM(TotNum_of_RASD_marked_obj_hits),
TotNum_of_RASD_marked_obj_miss = SUM(TotNum_of_RASD_marked_obj_miss),
Total_online_log_read_time     = SUM(Total_online_log_read_time    )

    from ".$ServerName."_RAOSTATS
    where Timestamp >='".$StartTimestamp."'
    and Timestamp <='".$EndTimestamp."'

";

?>
